# Асинхронный или неасинхронный запуск пауков (только для отладки)
async: true
# Запуск в отладочном режиме или в рабочем
debug: false
# Сохранять файлы или производить запись в БД?  (только для отладки)
store_files: false
# Количество потоков на сайт (лучше не более 4)
crawler_per_site: 4
# Папка со скриптами для парсинга контента сайтов
script_dir: /tmp/crawler/scripts
# Блок с настройками для анализируемых сайтов
sites:
   # На каждый сайт. Название домена (будет использоваться для идентфикации и записи в БД)
 - domain: bnkomi.ru
   # На каждый сайт. стартовая страница для парсинга
   seed: http://bnkomi.ru
# Каталог для сохранения данных о результатах парсинга сайта (для каждого сайта
# создается подпапка с именем домена для хранения соотвествующих данных)
storage_dir: /tmp/crawler
# строка подключения к MongoDB для сохранения результатаов анализа
connection_url: mongodb://localhost:27017/
# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
